export const styles = {
  app: { display: 'flex', minHeight: '100vh', background: '#f8fafc', fontFamily: "'Plus Jakarta Sans', sans-serif" },
  sidebar: { width: '250px', background: 'linear-gradient(135deg, #1e293b 0%, #0f172a 100%)', color: 'white', padding: '30px 20px', boxShadow: '0 4px 12px rgba(0,0,0,0.1)', position: 'fixed', height: '100vh', left: 0, top: 0, overflowY: 'auto' },
  logo: { fontSize: '20px', fontWeight: 'bold', marginBottom: '40px', textAlign: 'center', paddingBottom: '20px', borderBottom: '1px solid rgba(255,255,255,0.1)' },
  nav: { display: 'flex', flexDirection: 'column', gap: '10px' },
  navBtn: { background: 'transparent', color: '#94a3b8', border: 'none', padding: '12px 15px', borderRadius: '8px', cursor: 'pointer', fontSize: '14px', fontWeight: '500', transition: 'all 0.2s', textAlign: 'left' },
  navBtnActive: { background: 'rgba(59, 130, 246, 0.2)', color: '#60a5fa', borderTop: 'none', borderRight: 'none', borderBottom: 'none', borderLeft: '3px solid #3b82f6' },
  main: { marginLeft: '250px', flex: 1, padding: '40px' },
  header: { marginBottom: '40px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' },
  h1: { fontSize: '32px', fontWeight: 'bold', color: '#0f172a', margin: '0 0 8px 0' },
  subtitle: { fontSize: '14px', color: '#64748b', margin: 0 },
  content: {},
  statsGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))', gap: '15px', marginBottom: '30px' },
  stat: { background: 'linear-gradient(135deg, #3b82f6 0%, #1e40af 100%)', color: 'white', padding: '25px', borderRadius: '12px', textAlign: 'center', boxShadow: '0 4px 12px rgba(0,0,0,0.08)' },
  statValue: { fontSize: '28px', fontWeight: 'bold', marginBottom: '8px' },
  statLabel: { fontSize: '12px', opacity: 0.9 },
  card: { background: 'white', borderRadius: '12px', padding: '25px', marginBottom: '20px', boxShadow: '0 1px 3px rgba(0,0,0,0.08)', border: '1px solid #e2e8f0' },
  cardTitle: { fontSize: '18px', fontWeight: '600', marginBottom: '20px', color: '#0f172a' },
  twoCol: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '20px' },
  form: { display: 'flex', flexDirection: 'column', gap: '12px' },
  formRow: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px' },
  input: { padding: '12px 14px', border: '1px solid #e2e8f0', borderRadius: '8px', fontSize: '14px', fontFamily: 'inherit', transition: 'border 0.2s' },
  btn: { padding: '12px 20px', background: 'linear-gradient(135deg, #3b82f6 0%, #1e40af 100%)', color: 'white', border: 'none', borderRadius: '8px', cursor: 'pointer', fontWeight: '600', fontSize: '14px', transition: 'transform 0.2s' },
  btnSmall: { background: 'none', border: 'none', cursor: 'pointer', fontSize: '16px', padding: '4px 8px' },
  list: { display: 'flex', flexDirection: 'column', gap: '10px' },
  listItem: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '12px 15px', background: '#f8fafc', borderRadius: '8px', border: '1px solid #e2e8f0', fontSize: '14px' },
  invoiceCard: { display: 'flex', alignItems: 'center', padding: '12px 15px', background: '#f8fafc', borderRadius: '8px', border: '1px solid #e2e8f0', marginBottom: '8px', gap: '10px' },
  summaryGrid: { display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '20px' },
  summaryItem: { padding: '20px', background: '#f8fafc', borderRadius: '8px', border: '1px solid #e2e8f0' },
  summaryLabel: { fontSize: '12px', color: '#64748b', marginBottom: '8px', fontWeight: '500' },
  loading: { textAlign: 'center', padding: '40px', fontSize: '16px', color: '#64748b' }
};
